module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/B5Zw2XPHrKjEFq00zrw8Y8',
    ADMIN_LIST_PATH: './admine.json',
    IMAGE_PATH: 'https://postimg.cc/nX6ZH38b',
    NEWSLETTER_JID: '120363399531796033@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗖𝗬𝗕𝗘𝗥 𝗔𝗡𝗨𝗪𝗛 𝗠𝗜𝗡𝗜 𝗠𝗗',
    OWNER_NAME: '𝗔𝗡𝗨𝗚𝗔 𝗦𝗘𝗡𝗜𝗧𝗛𝗨',
    OWNER_NUMBER: '94710695082',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝗣𝗢𝗪𝗘𝗥𝗘𝗗 𝗕𝗬 𝗔𝗡𝗨𝗚𝗔 𝗦𝗘𝗡𝗜𝗧𝗛𝗨',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb69q4Y8fewk9hwUdq28,
};
